# Generated by Django 5.0.2 on 2024-03-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelTableComment(
            name='status',
            table_comment='Status dos tickets do sistema.',
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['name'], name='status_name_idx'),
        ),
        migrations.AlterModelTable(
            name='status',
            table='status_ticket',
        ),
    ]
