# Generated by Django 5.0.2 on 2024-03-18 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='files/tickets/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticketss',
                'db_table': 'ticket',
                'db_table_comment': 'Tickets dos usuários do sistema.',
                'indexes': [models.Index(fields=['title'], name='ticket_name_idx')],
            },
        ),
    ]
